sudo: false
language: go

services:
- redis-server

go:
  - 1.6
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get gopkg.in/redis.v4
  - go get gopkg.in/vmihailenco/msgpack.v2
  - mkdir -p $HOME/gopath/src/gopkg.in/go-redis/
  - mv `pwd` $HOME/gopath/src/gopkg.in/go-redis/cache.v4

before_script:
  - redis-server --port 6380 &
